package sg.nus.carelink.profile.infrastructure.persistence.adapter;

import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Repository;

import jakarta.persistence.EntityManager;

import sg.nus.carelink.profile.domain.model.ElderFamilyBinding;
import sg.nus.carelink.profile.domain.repository.ElderFamilyBindingRepository;
import sg.nus.carelink.profile.infrastructure.persistence.entity.ElderFamilyBindingJpaEntity;
import sg.nus.carelink.profile.infrastructure.persistence.repository.ElderFamilyBindingJpaRepository;

/**
 * Implements the elder-family binding domain repository using Spring Data.
 *
 * <p>The database owns created_at and updated_at. After saving, the adapter
 * flushes the SQL and refreshes the managed entity so database-generated
 * timestamp values are available before mapping back to the domain model.
 */
@Repository
class ElderFamilyBindingRepositoryAdapter
        implements ElderFamilyBindingRepository {

    private final ElderFamilyBindingJpaRepository jpa;
    private final EntityManager entityManager;

    ElderFamilyBindingRepositoryAdapter(
            ElderFamilyBindingJpaRepository jpa,
            EntityManager entityManager) {

        this.jpa = jpa;
        this.entityManager = entityManager;
    }

    @Override
    public Optional<ElderFamilyBinding> findById(Long id) {
        return jpa.findById(id)
                .map(ElderFamilyBindingMapper::toDomain);
    }

    @Override
    public List<ElderFamilyBinding> findByElderId(
            Long elderId) {

        return jpa
                .findByElderIdOrderByCreatedAtDesc(elderId)
                .stream()
                .map(ElderFamilyBindingMapper::toDomain)
                .toList();
    }

    @Override
    public List<ElderFamilyBinding> findByFamilyMemberId(Long familyMemberId) {
        return jpa.findByFamilyMemberIdOrderByElderIdAsc(familyMemberId).stream()
                .map(ElderFamilyBindingMapper::toDomain)
                .toList();
    }

    @Override
    public Optional<ElderFamilyBinding>
            findByElderIdAndFamilyMemberId(
                    Long elderId,
                    Long familyMemberId) {

        return jpa
                .findByElderIdAndFamilyMemberId(
                        elderId,
                        familyMemberId
                )
                .map(ElderFamilyBindingMapper::toDomain);
    }

    @Override
    public ElderFamilyBinding save(
            ElderFamilyBinding elderFamilyBinding) {

        ElderFamilyBindingJpaEntity entity =
                ElderFamilyBindingMapper.toEntity(
                        elderFamilyBinding
                );

        /*
         * saveAndFlush() is intentional here.
         *
         * created_at and updated_at are generated by MySQL, not by the
         * application. The SQL must therefore reach the database before the
         * entity can be refreshed with those generated values.
         */
        ElderFamilyBindingJpaEntity saved =
                jpa.saveAndFlush(entity);

        /*
         * Reload database-managed columns such as created_at and updated_at
         * into the managed JPA entity.
         */
        entityManager.refresh(saved);

        return ElderFamilyBindingMapper.toDomain(
                saved
        );
    }
}
